name: webRTC CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: docker login
        run: |
          docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}

      - name: build peer server image
        run: |
          cd peerServerConfig
          docker build -t akshit8/peer:latest -f ./peer.dockerfile .
          cd ..

      - name: build app image
        run: |
          docker build -t akshit8/webRTC:latest -f ./app.dockerfile .

      - name: push peer server image
        run: |
          docker push akshit8/peer:latest

      - name: push app image
        run: |
          docker push akshit8/webRTC:latest

      